% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Nov-2022 20:42:17
%  MATLAB version: 9.12.0.1956245 (R2022a) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

phi = saveVarsMat.phi; % <10628577x1713600 double> too many elements

clear saveVarsMat;
