#!/bin/sh

#'112111' '128221' '130519' '170192' '176117' '208010' '210022' '211787' '214685' '232237' '308597' '324038' '330406' '346878'
for subject in '112111'
    do
    mask='/data/underworld/home/kbas/03_data/processed_dif/'$subject'/amygdala_mask_diff.nii.gz'
    target=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path "*/dwi/qmap-preproc-dwimask/nodif_brain_mask.nii.gz")
    csf=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path '*/dwi/qmap-preproc-dwimask/sub-'$subject'_ses-*_space-orig_desc-dwi-csf_mask.nii')
    bedpostx=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path '*/dwi/fsl-preproc-bedpostx')'/merged'
    # nodif_brain_mask=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path '*/dwi/fsl-preproc-bedpostx')'/nodif_brain_mask'
    # nodif_brain_mask=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path '*/dwi/qmap-preproc_dwimask')'/nodif_brain_mask'
    nodif_brain_mask=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path "*/dwi/qmap-preproc-dwimask/nodif_brain_mask.nii.gz")
    output_dir=$(find '/data/underworld/home/kbas/03_data/derivatives/'$subject -path '*/dwi')'/fsl-probtrackx-2'
    echo $mask
    echo $target
    echo $csf
    echo $bedpostx
    echo $nodif_brain_mask
    echo $output_dir
    echo

    run_command="probtrackx2 -x $mask -l --omatrix2 --target2=$target -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --stop=$csf --forcedir --opd -s $bedpostx -m $nodif_brain_mask --dir=$output_dir"
    eval $run_command

    done